### ISSUE TITLE
So how can I get a zip package to flash into my device?

### ISSUE THREAD

**Issue by BerialJ** [DroidKali/santoni_kernel_nethunter#1]
failed on that..

**Comment by DroidKali** [comment]
You can use [this](https://github.com/jcadduono/lazyflasher.git) or go to xda or Google search how to repack flashable zip package😁

**Comment by DroidKali** [comment]
You can use [this](https://github.com/jcadduono/lazyflasher) or go to xda or Google search how to repack flashable zip package😁
