### ISSUE TITLE
Getting error 1 while flashing nethunter zip 

### ISSUE THREAD

**Issue by mycal123** [DroidKali/santoni_kernel_nethunter#2]
![IMG_20211202_111546](https://user-images.githubusercontent.com/59077033/144365684-cc11e4b5-0363-40bf-bc50-8447688f8e19.jpg)

I followed the steps below. Phone is redmi 4x santoni code name. Running on lineage os 16.1 nauget based. But unable to flash nethunter-2021.3-generic-arm64 zip
_-________--_____---___---__============

Step 1: Reflash your stock Oreo ROM

Step 2: OTA update to nougat to bring modem and bootloader up to date. THIS MUST BE DONE BY OTA, NOT DIRECT FLASH OF NOUGAT.

Step 3: Install a nougat custom rom, I recommend lineage.

Step 4: flash this zip: https://kali.download/nethunter-images/kali-2021.3/nethunter-2021.3-generic-arm64-kalifs-full.zip

Step 5: Build and flash this kernel. If you can't do this step me or one of the other helpers may be able to help do it for you. https://github.com/DroidKali/santoni_kernel_nethunter

**Comment by theanontemp** [comment]
Im also getting the same error

here is the recovey.log

inflating: /tmp/nethunter/system/etc/terminfo/r/rxvt
inflating: /tmp/nethunter/data/app/RFAnalyzer.apk
/tmp/updater[129]: .: env.sh: No such file or directory
Updater process ended with ERROR: 1
I:Install took 68 second(s).

**Comment by DroidKali** [comment]
You should to use magisk to install the NetHunter Generic zip
